### ISSUE TITLE
Is it possible to exclude some tests via configuration?

### ISSUE THREAD

**Issue by AlexKorovyansky** [wiredrive/wtframework#49]
I need to avoid running of concrete tests in production, while have it for staging. I can switch urls, test accounts and other stuff using configuration yaml files. For me it looks it should be useful to have possibility to exclude some tests via configuration file, else I can imagine usage of branching to solve the problem, but it looks much more boilerplate way.

What's your thoughts, guys?

**Comment by dlai0001** [comment]
You can use Nosetest's (the underlying unittest framework) tags to tag your tests, then pass in some nose tag filter to target or exclude tests.  You can associate a test with any number of tags.

http://nose.readthedocs.org/en/latest/plugins/attrib.html

I like using multiple tags to differentiate tests by
a) type of tests - smoke, regression, etc...
b) features - user_management, account_creation, etc...
c) any exclude tags - exclude_www, exclude_firefox, etc...

Then in the build plans, you can add these as extra parameters into nosetests.

**Comment by AlexKorovyansky** [comment]
It makes sense! Thanks!
