### ISSUE TITLE
How to set the extensions path for all browsers in WTFramework?

### ISSUE THREAD

**Issue by ykelanemer** [wiredrive/wtframework#52]
Hi,

First of all, I would like to thank you for developing this very nice framework. I have been using it for almost a year and I like it a lot.

I am testing a web application which uses a player to display 3D Design. Since Selenium creates a new profile if we don't specify one, the new instance of the browser cannot find the add-ons for Firefox for example. It is the same with Chrome. Every time you run a test, it asks you to reinstall the player.

To work around this issue with Firefox, I specified the path to the profile I want to use in the framework file wtf\web\webdriver.py. First in the import:

     from selenium.webdriver.firefox.firefox_profile import FirefoxProfile

and then in the method:

     def __create_driver_from_browser_config(self):

line 178:            

       self.FIREFOX: lambda: webdriver.Firefox(FirefoxProfile('C:\\...\\Mozilla\\Firefox\\Profiles\\25srvujx.default')),

and it works just fine.

My questions:

1. Does WTFramework address this need for setting the browser profile or at least setting the extensions path? If yes how?

2. If not, How can I make my fix more elegant by using config file?

3. How can I build a solution for all type of browsers, at least Firefox, Chrome and IE? 

Thanks a lot for your help!

Youcef Kelanemer
QA

**Comment by dlai0001** [comment]
When I originally designed WTF, I didn't have that use case in mind.

I think getting it to work on all browser is essentially creating something that checks for a profile config, somewhere around this line, https://github.com/wiredrive/wtframework/blob/master/wtframework/wtf/web/webdriver.py#L130

Then add some sort of profile support around where the webdriver is being instantiated,
https://github.com/wiredrive/wtframework/blob/master/wtframework/wtf/web/webdriver.py#L179

**Comment by ykelanemer** [comment]
Thanks David for your fast answer! I will try it.
Youcef

**Comment by ykelanemer** [comment]
Hi David,

I added 2 optional config variables in default.yaml under desired_capabilities section. If the configs are absent or empty, the framework works as before.

  desired_capabilities:

    #Browser profile path if you want Selenium to use a specific profile for the browser
    chrome_profile_path: C:\Users\user_qa\AppData\Local\Google\Chrome\User Data
    firefox_profile_path: C:\Users\user_qa\AppData\Roaming\Mozilla\Firefox\Profiles\25srvujx.default
 

And in the web/webdriver file, I added this code to the method (around line 177)
    def __create_driver_from_browser_config(self):

         if browser_type == 'FIREFOX':
            FIREFOX_PROFILE_PATH = WTF_CONFIG_READER.get('selenium.desired_capabilities.firefox_profile_path', None)
        elif browser_type == 'CHROME':
            CHROME_PROFILE_PATH = WTF_CONFIG_READER.get('selenium.desired_capabilities.chrome_profile_path', None)
            chrome_options = Options()
            if CHROME_PROFILE_PATH:
                chrome_options.add_argument("test-type")
                chrome_options.add_argument("--user-data-dir=" + CHROME_PROFILE_PATH)

				# and modified the 2 first entries of browser dictionary in the same method.
        browser_type_dict = {
            self.CHROME: lambda: webdriver.Chrome(self._config_reader.get(WebDriverFactory.CHROME_DRIVER_PATH), chrome_options=chrome_options),
            self.FIREFOX: lambda: webdriver.Firefox(FirefoxProfile(FIREFOX_PROFILE_PATH)),


I did not need to add any thing for the case IE. It works fine with the 3 browsers.


Thanks,
I am closing this issue.
